name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python v${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run : |
          python -m pip install --upgrade pip setuptools wheel
          pip install .

      - name: Run linter
        run: |
          pip install '.[lint]'
          ruff check --output-format=github .
        continue-on-error: true

      - name: Run tests
        run: |
          pip install '.[test]'
          pytest